pipeline {
    agent {
        node {
            label 'openjdk-24-jdk'
        }
    }

    stages {
        stage('Build Image') {
            steps {
                sh 'jar -cfe0 hello.jar Hello Hello.java Goodbye.java'
            }
        }
    }
}
