pipeline {
    agent {
        node {
            label 'workers-ladybird-clang-18'
        }
    }

    stages {
        stage('Clone Ladybird') {
            steps {
                sh 'javac -d . jobs/openjdk-jar/Hello.java jobs/openjdk-jar/Goodbye.java'
                sh 'jar -v0cfe hello.jar Hello Hello.class Goodbye.class'
            }
        }

        stage('Run Buildscript') {
            steps {
                sh 'java -jar hello.jar'
            }
        }
    }
}
