pipeline {
    agent {
        node {
            label 'workers-ladybird-clang-18-cache'
        }
    }

    stages {
        stage('Pull Latest') {
            steps {
                //sh 'mv ~/ladybird ./ladybird'
                sh "cd ~/ladybird; git fetch; git checkout ${params.branch}; git pull;"
            }
        }
        
        stage('Build Latest') {
            steps {
                sh "cd ~/ladybird; ./Meta/ladybird.sh build ladybird;"
            }
        }

        stage('Archive Build') {
            steps {
                sh 'mv ~/ladybird/Build .; zip -r Build.zip Build'
                archiveArtifacts 'Build.zip'
            }
        }
    }
}
