pipeline {
    agent {
        node {
            label 'workers-ladybird-clang-18'
        }
    }

    stages {
        stage('Clone Ladybird') {
            steps {
                sh 'git clone https://github.com/LadybirdBrowser/ladybird.git'
            }
        }

        stage('Run Buildscript') {
            steps {
                sh './ladybird/Meta/ladybird.sh run ladybird'
            }
        }
    }
}
