pipeline {
    agent {
        node {
            label 'workers-openjdk'
        }
    }

    stages {
        stage('Build Jarfile') {
            steps {
                sh 'javac -d . jobs/openjdk-jar/Hello.java jobs/openjdk-jar/Goodbye.java'
                sh 'jar -v0cfe hello.jar Hello Hello.class Goodbye.class'
            }
        }

        stage('Run Jarfile') {
            steps {
                sh 'java -jar hello.jar'
            }
        }
        
        stage('Archive Jarfile') {
            steps {
                archiveArtifacts 'hello.jar'
            }
        }
    }
}
